export const FETCH_NYT_ARTICLES = 'FETCH_NYT_ARTICLES';
export const LOADING_ARTICLES = 'LOADING_ARTICLES';
export const NO_ARTICLES = 'NO_ARTICLES';

export const FETCH_DICTIONARY = 'FETCH_DICTIONARY';
export const LOADING_DICTIONARY = 'LOADING_DICTIONARY';
export const NO_DEFINITION = 'NO_DEFINITION';
